/**
 * A/B for nexttask 1 — does turning a SKIPPED boot check into an UNOBSERVED
 * verdict remove the run-18 shape ("the app was never observed to boot" and "the
 * app booted fine" produce byte-identical gate output) without blocking anything?
 *
 * Deterministic: no model, no PI_BIN, no llama-server. Both arms are the REAL
 * `runFinalIntegrationGate` — the baseline is the module as shipped at
 * BASELINE_REF, extracted with `git show` into a sibling file so its relative
 * imports still resolve, the treatment is the working tree. They run in ONE
 * process over the same corpus, each on its own fresh clone, so a tree the first
 * arm mutated (`lint --fix`, `build`, `migrate`) can never bias the second.
 *
 * BASELINE_REF is PINNED, not `HEAD`. Once the lever lands, `HEAD` contains it and
 * a re-run would silently compare the lever against itself and report a triumphant
 * ABSTAIN-shaped zero. The pin is the pre-lever release.
 *
 * Pre-registered metric, mechanical: per tree the tuple
 *   (verdict, reason contains the boot label, `unobserved` set)
 * and the target shape is a tree where the boot command was DISCOVERED, SKIPPED,
 * the project is a served app, and the gate still returned a bare PASS.
 *
 * Verdicts (scripts/ab-verdict.ts): PASS exit 0, FAIL exit 1, ABSTAIN exit 2.
 *
 * Run: bun run scripts/boot-skip-verdict-ab.ts
 */
import {spawnSync} from 'node:child_process'
import {existsSync, rmSync, writeFileSync} from 'node:fs'
import * as path from 'node:path'
import {
    discoverBootCommand,
    detectsServedApp,
    runBootCheck,
    preferredDeclaredPort,
    runFinalIntegrationGate,
    type BootDeps,
    type FinalGateOutcome
} from '../src/task/final-gate.js'
import {runRenderCheck} from '../src/task/render-check.js'
import {runDeepRenderCheck} from '../src/task/deep-render-check.js'
import {reportAb, type Invariant} from './ab-verdict.js'
import {
    FIXTURE_CORPUS,
    REPO,
    REPO_CORPUS,
    installDockerlessShim,
    makeWorkRoot,
    materialise,
    verdictOf,
    type BootClass,
    type CorpusEntry
} from './boot-skip-corpus.js'

/** v0.24.4 — the last release before the skip→UNOBSERVED lever. */
const BASELINE_REF = process.env.BOOT_SKIP_BASELINE_REF ?? '8425ae8'
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'final-gate.baseline.gen.ts')

type GateFn = (
    cwd: string,
    timeoutMs?: number,
    bootGraceMs?: number,
    bootDeps?: BootDeps,
    planText?: string
) => Promise<FinalGateOutcome>

/** The shipped module, materialised next to its own dependencies so `./x.js`
 *  imports resolve exactly as they do for the real one. */
async function loadBaselineGate(): Promise<GateFn> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/final-gate.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read final-gate.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/boot-skip-verdict-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    const mod: unknown = await import(BASELINE_FILE)
    // Delete it the instant it is loaded: pi-task itself is in the corpus, and a
    // clone taken while this file existed would typecheck and lint a stray duplicate
    // module — the harness must not perturb the tree it is measuring.
    rmSync(BASELINE_FILE, {force: true})
    return (mod as {runFinalIntegrationGate: GateFn}).runFinalIntegrationGate
}

interface ArmResult {
    verdict: 'PASS' | 'UNOBSERVED' | 'FAIL'
    reasonHasBootLabel: boolean
    unobservedSet: boolean
    reason: string
    unobserved: string
}

interface TreeResult {
    label: string
    bootLabel: string | null
    expectServer: boolean
    boot: BootClass
    baseline: ArmResult
    treatment: ArmResult
}

function arm(out: FinalGateOutcome, bootLabel: string | null): ArmResult {
    return {
        verdict: verdictOf(out),
        reasonHasBootLabel: bootLabel !== null && out.reason.includes(`\`${bootLabel}\``),
        unobservedSet: out.unobserved !== undefined,
        reason: out.reason,
        unobserved: out.unobserved ?? ''
    }
}

/** The tuple the A/B compares. Anything outside it is reporting, not metric. */
function tuple(a: ArmResult): string {
    return `${a.verdict}|boot-label:${a.reasonHasBootLabel}|unobserved:${a.unobservedSet}`
}

/** Bare PASS over a discovered-but-skipped boot on a SERVED app — the shape the
 *  lever must remove. CLI projects are deliberately outside it (inv-cli-unaffected). */
function isTargetShape(t: TreeResult, a: ArmResult): boolean {
    return t.bootLabel !== null && t.boot === 'skip' && t.expectServer && a.verdict === 'PASS'
}

const work = makeWorkRoot('ab')
installDockerlessShim(work)
const results: TreeResult[] = []

const filters = process.argv.slice(2)
const corpus = [...REPO_CORPUS, ...FIXTURE_CORPUS].filter(
    e => filters.length === 0 || filters.some(f => e.label.includes(f))
)

async function runTree(entry: CorpusEntry, baselineGate: GateFn): Promise<void> {
    if (entry.kind === 'repo' && !existsSync(entry.source)) {
        console.log(`\n${entry.label}: SKIP (missing)`)
        return
    }
    const slug = entry.label.replace(/[^\w.@-]+/g, '_')
    const timeout = entry.timeoutMs ?? 300_000

    // Arm 1 — the module as shipped.
    const baseDir = materialise(entry, path.join(work, `${slug}.baseline`))
    const boot = discoverBootCommand(baseDir)
    const bootLabel = boot ? `${boot[0]} ${boot[1].join(' ')}` : null
    const expectServer = detectsServedApp(baseDir)
    let bootClass: BootClass = 'none'
    if (boot) {
        const deps: BootDeps = {
            renderProbe: runRenderCheck,
            deepRenderProbe: url => runDeepRenderCheck(url, baseDir),
            preferredPort: () => preferredDeclaredPort(baseDir)
        }
        bootClass = (await runBootCheck(baseDir, boot, 10_000, {expectServer, deps})).outcome
    }
    const baseOut = await baselineGate(baseDir, timeout)
    rmSync(baseDir, {recursive: true, force: true})

    // Arm 2 — the working tree, on a clone made from the same pristine source.
    const treatDir = materialise(entry, path.join(work, `${slug}.treatment`))
    const treatOut = await runFinalIntegrationGate(treatDir, timeout)
    rmSync(treatDir, {recursive: true, force: true})

    const t: TreeResult = {
        label: entry.label,
        bootLabel,
        expectServer,
        boot: bootClass,
        baseline: arm(baseOut, bootLabel),
        treatment: arm(treatOut, bootLabel)
    }
    results.push(t)
    console.log(`\n=== ${t.label}`)
    console.log(`  boot ${t.bootLabel ?? 'none'} → ${t.boot}   expectServer ${t.expectServer}`)
    console.log(`  BASELINE  ${tuple(t.baseline)}`)
    console.log(`            ${t.baseline.reason.slice(0, 200).replace(/\n/g, ' | ')}`)
    console.log(`  TREATMENT ${tuple(t.treatment)}`)
    console.log(`            ${t.treatment.reason.slice(0, 200).replace(/\n/g, ' | ')}`)
    console.log(
        `  target shape: baseline ${isTargetShape(t, t.baseline) ? 'YES' : 'no'} → `
            + `treatment ${isTargetShape(t, t.treatment) ? 'YES' : 'no'}`
    )
}

try {
    const baselineGate = await loadBaselineGate()
    console.log(`baseline: final-gate.ts @ ${BASELINE_REF}`)
    console.log(`treatment: working tree`)
    console.log(`work dir: ${work}`)
    console.log("docker/docker-compose shimmed to exit 127 (reproducing run 18's sandbox)")
    for (const entry of corpus) await runTree(entry, baselineGate)

    const unchanged = (t: TreeResult): boolean =>
        tuple(t.baseline) === tuple(t.treatment)
        && t.baseline.reason === t.treatment.reason
        && t.baseline.unobserved === t.treatment.unobserved

    const brokeNewFail = results.filter(
        t => t.baseline.verdict !== 'FAIL' && t.treatment.verdict === 'FAIL'
    )
    const bootPassChanged = results.filter(t => t.boot === 'pass' && !unchanged(t))
    const nothingToBootChanged = results.filter(t => t.bootLabel === null && !unchanged(t))
    const cliChanged = results.filter(t => !t.expectServer && !unchanged(t))

    const detail = (list: TreeResult[]): string | undefined =>
        list.length === 0 ? undefined : list.map(t => t.label).join('; ')

    const invariants: Invariant[] = [
        {
            label: 'inv-no-new-fail — no tree moves PASS/UNOBSERVED → FAIL',
            ok: brokeNewFail.length === 0,
            detail: detail(brokeNewFail)
        },
        {
            label: 'inv-boot-pass-untouched — boot `pass` trees byte-identical',
            ok: bootPassChanged.length === 0,
            detail: detail(bootPassChanged)
                ?? `${results.filter(t => t.boot === 'pass').length} tree(s) checked`
        },
        {
            label: 'inv-nothing-to-boot — no boot command ⇒ unchanged',
            ok: nothingToBootChanged.length === 0,
            detail: detail(nothingToBootChanged)
                ?? `${results.filter(t => t.bootLabel === null).length} tree(s) checked`
        },
        {
            label: 'inv-cli-unaffected — expectServer false ⇒ unchanged',
            ok: cliChanged.length === 0,
            detail: detail(cliChanged)
                ?? `${results.filter(t => !t.expectServer).length} tree(s) checked`
        }
    ]

    console.log('\n\n  per-tree (label | boot | baseline tuple | treatment tuple):')
    for (const t of results) {
        console.log(
            `    ${t.label.padEnd(44)} ${t.boot.padEnd(12)} `
                + `${tuple(t.baseline).padEnd(46)} ${tuple(t.treatment)}`
        )
    }

    reportAb({
        name: 'boot-skip → UNOBSERVED verdict',
        reps: results.length,
        targetShape:
            'a tree whose boot command was DISCOVERED and SKIPPED on a served app, '
            + 'and whose gate still returned a bare PASS',
        baselineHits: results.filter(t => isTargetShape(t, t.baseline)).length,
        treatmentHits: results.filter(t => isTargetShape(t, t.treatment)).length,
        invariants
    })
} finally {
    rmSync(BASELINE_FILE, {force: true})
    rmSync(work, {recursive: true, force: true})
}
