/**
 * A/B for nexttask 2 part A — does rejecting NON-LAUNCH scripts stop the gate
 * from resolving its boot command to a container-orchestration script?
 *
 * THE SHAPE (mx5 run 18, measured). `discoverBootCommand` takes `start`, else
 * `dev`. Run 18 has no `start`, and its `dev` is
 *
 *     docker compose -f docker-compose.dev.yml up -d && until docker compose … \
 *       pg_isready …; done && concurrently "bun run dev:css" "bun run dev:js" \
 *       "bun run --watch src/server/index.ts"
 *
 * The gate sandbox has no docker, so the chain died at 127 and the boot SKIPPED as
 * an environment gap — an unfalsifiable outcome, produced for an app that had no
 * HTTP listener anywhere in its source. The command chosen was never a launch of
 * the shipped app in the first place.
 *
 * ARMS. Baseline = `discoverBootCommand` as shipped at BASELINE_REF (extracted with
 * `git show` into a sibling file so its relative imports still resolve); treatment =
 * the working tree. Discovery is a PURE function of the tree, so both arms read the
 * corpus READ-ONLY and no clone is needed for the metric itself.
 *
 * PRE-REGISTERED METRIC, per tree: `(command chosen, boot outcome)`. The target
 * shape is *a tree whose chosen command is infra-orchestration and whose boot
 * outcome is `skip`*. "Infra-orchestration" is judged by a literal regex local to
 * this harness (INFRA_SHAPE_RE below), never by the module under test — a lever may
 * not define its own target shape.
 *
 * BOOT OUTCOMES ARE MEASURED, NOT ASSUMED, and only where they can differ: a tree
 * both arms resolve identically boots identically by construction (same command,
 * same tree), so a boot is executed only for trees where the arms DISAGREE, plus
 * every fixture that exists to prove a real dev script still boots. Real repos boot
 * in a throwaway clone; the corpus is never written to.
 *
 * THE DOCKERLESS SHIM, DISCLOSED. As in scripts/boot-skip-corpus.ts, `docker` and
 * `docker-compose` are shimmed to exit 127 for this process and its children, which
 * reproduces run 18's recorded sandbox exactly. This box DOES have docker, and
 * without the shim the baseline arm's mx5 boot would start real containers on the
 * user's machine — a side effect no measurement justifies. What the shim costs is
 * disclosed rather than hidden: on a docker-HAVING box the baseline chain would get
 * past `up -d` and run the `concurrently` watchers, so mx5's baseline boot outcome
 * there could be `pass`-shaped rather than `skip`. That possibility is exactly what
 * part B settles statically — mx5 has no bind anywhere in its tree, so nothing in
 * that chain can serve — and it is why the invariant below is stated over trees that
 * were OBSERVED to boot rather than over trees that might have.
 *
 * Verdicts (scripts/ab-verdict.ts): PASS exit 0, FAIL exit 1, ABSTAIN exit 2.
 *
 * Run: bun run scripts/boot-command-resolution-ab.ts
 */
import {spawnSync} from 'node:child_process'
import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync} from 'node:fs'
import * as path from 'node:path'
import {
    detectsServedApp,
    discoverBootCommand,
    preferredDeclaredPort,
    runBootCheck
} from '../src/task/final-gate.js'
import type {HealthCommand} from '../src/task/repo-health-check.js'
import {reportAb, type Invariant} from './ab-verdict.js'
import {HUB, REPO, installDockerlessShim, makeWorkRoot} from './boot-skip-corpus.js'

/** v0.24.5 — the last release before the non-launch rejection. PINNED, not HEAD:
 *  once the lever lands, HEAD contains it and the A/B would compare it to itself. */
const BASELINE_REF = process.env.BOOT_CMD_BASELINE_REF ?? '1e15b8b'
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'final-gate.bootcmd-baseline.gen.ts')

type DiscoverFn = (cwd: string) => HealthCommand | null

async function loadBaselineDiscover(): Promise<DiscoverFn> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/final-gate.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read final-gate.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/boot-command-resolution-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    const mod: unknown = await import(BASELINE_FILE)
    rmSync(BASELINE_FILE, {force: true})
    return (mod as {discoverBootCommand: DiscoverFn}).discoverBootCommand
}

/**
 * The harness's OWN definition of an infra-orchestration script body: the first
 * member of the chain invokes a container tool and hands it an `up`/`start` verb.
 * Deliberately independent of nonLaunchScriptReason — the metric must not be
 * whatever the treatment happens to reject.
 */
const INFRA_SHAPE_RE = /^[^&|;]*\b(?:docker|podman|nerdctl)(?:[-\s]compose)?\b[^&|;]*\b(?:up|start)\b/

function scriptsOf(dir: string): Record<string, string> {
    try {
        const j = JSON.parse(readFileSync(path.join(dir, 'package.json'), 'utf8')) as {
            scripts?: Record<string, string>
        }
        return j.scripts ?? {}
    } catch {
        return {}
    }
}

/** The script BODY behind a chosen `bun run <name>`, or '' for make/none. */
function bodyOf(dir: string, cmd: HealthCommand | null): string {
    if (!cmd || cmd[0] !== 'bun' || cmd[1][0] !== 'run') return ''
    return scriptsOf(dir)[cmd[1][1]] ?? ''
}

const label = (cmd: HealthCommand | null): string => (cmd ? `${cmd[0]} ${cmd[1].join(' ')}` : 'none')

type BootClass = 'none' | 'pass' | 'fail' | 'skip' | 'orphan-port'

interface TreeResult {
    label: string
    dir: string
    baselineCmd: string
    treatmentCmd: string
    baselineBody: string
    /** Measured, or 'none' when there was no command; '' when not measured. */
    baselineBoot: BootClass | ''
    treatmentBoot: BootClass | ''
    /** A fixture whose dev script is a plain server launch (inv-real-dev-kept). */
    realDevFixture: boolean
}

async function bootOutcome(dir: string, cmd: HealthCommand | null): Promise<BootClass> {
    if (!cmd) return 'none'
    const expectServer = detectsServedApp(dir)
    const r = await runBootCheck(dir, cmd, 8_000, {
        expectServer,
        // The render probes are deliberately NOT injected: this A/B measures which
        // command is chosen and whether it comes up, not what the page looks like.
        deps: {preferredPort: () => preferredDeclaredPort(dir)}
    })
    return r.outcome
}

// ---------------------------------------------------------------------------
// Fixtures. Each pins ONE decision; the two `real-dev` ones carry the invariant
// that a genuine server watch must still be accepted (and must still BOOT).
// ---------------------------------------------------------------------------

interface Fixture {
    key: string
    /** package.json for the fixture. */
    pkg: Record<string, unknown>
    files?: Record<string, string>
    /** Run the boot in BOTH arms — used by the real-dev invariant fixtures. */
    measureBoot?: boolean
    realDev?: boolean
    note: string
}

/** A server that honours PORT so the boot check's ownership probe can see it. */
const SERVE_TS =
    'const port = Number(process.env.PORT ?? 0)\n'
    + 'Bun.serve({port, fetch: () => new Response("<h1>fixture</h1>", '
    + '{headers: {"content-type": "text/html"}})})\n'
    + 'setInterval(() => {}, 1000)\n'

const served = {hono: '4.12.27'}

const FIXTURES: Fixture[] = [
    {
        key: 'fx-docker-dev',
        pkg: {
            name: 'fx-docker-dev',
            private: true,
            dependencies: served,
            scripts: {
                dev: 'docker compose -f docker-compose.dev.yml up -d && concurrently "bun run dev:css" "bun run --watch serve.ts"',
                'dev:css': 'tailwindcss -i a.css -o b.css --watch'
            }
        },
        files: {'serve.ts': SERVE_TS},
        measureBoot: true,
        note: 'THE TARGET SHAPE — run 18 in miniature: orchestration first, watchers after'
    },
    {
        key: 'fx-watchers-only',
        pkg: {
            name: 'fx-watchers-only',
            private: true,
            dependencies: served,
            scripts: {
                dev: 'concurrently "tailwindcss -i a.css -o b.css --watch" "tsc --watch --preserveWatchOutput"'
            }
        },
        measureBoot: true,
        note: 'multiplexer whose every child is an ASSET watcher — nothing in it can listen'
    },
    {
        key: 'fx-real-dev-watch',
        pkg: {
            name: 'fx-real-dev-watch',
            private: true,
            dependencies: served,
            scripts: {dev: 'bun run --watch serve.ts'}
        },
        files: {'serve.ts': SERVE_TS},
        measureBoot: true,
        realDev: true,
        note: 'inv-real-dev-kept — a plain server watch must still be chosen AND still boot'
    },
    {
        key: 'fx-real-dev-mux',
        pkg: {
            name: 'fx-real-dev-mux',
            private: true,
            dependencies: served,
            scripts: {
                dev: 'concurrently "tailwindcss -i a.css -o b.css --watch" "bun run --watch serve.ts"'
            }
        },
        files: {'serve.ts': SERVE_TS},
        realDev: true,
        note: 'inv-real-dev-kept — a multiplexer with ONE serving child is still a launch'
    },
    {
        key: 'fx-real-dev-vite',
        pkg: {
            name: 'fx-real-dev-vite',
            private: true,
            dependencies: served,
            scripts: {dev: 'vite'}
        },
        realDev: true,
        note: 'inv-real-dev-kept — the framework dev server shape (vite/next dev)'
    },
    {
        key: 'fx-start-node',
        pkg: {
            name: 'fx-start-node',
            private: true,
            dependencies: served,
            scripts: {start: 'node server.js', dev: 'docker compose up'}
        },
        files: {'server.js': 'require("http").createServer((_q,s)=>s.end("ok")).listen(0)\n'},
        realDev: true,
        note: 'a real `start` wins before `dev` is ever considered — unchanged by the lever'
    }
]

function buildFixture(fx: Fixture, dir: string): void {
    mkdirSync(dir, {recursive: true})
    writeFileSync(path.join(dir, 'package.json'), `${JSON.stringify(fx.pkg, null, 4)}\n`)
    for (const [rel, body] of Object.entries(fx.files ?? {})) {
        writeFileSync(path.join(dir, rel), body)
    }
}

// ---------------------------------------------------------------------------

const work = makeWorkRoot('bootcmd')
installDockerlessShim(work)
const results: TreeResult[] = []

/** Real trees: pi-task plus every sibling checkout under ~/hub — the corpus widens
 *  with the box rather than being pinned to whatever existed when this was written. */
function realTrees(): Array<{label: string; dir: string}> {
    const out = [{label: 'pi-task (self)', dir: REPO}]
    if (existsSync(HUB)) {
        for (const name of readdirSync(HUB).sort()) {
            const dir = path.join(HUB, name)
            if (existsSync(path.join(dir, 'package.json')) || existsSync(path.join(dir, 'Makefile'))) {
                out.push({label: name, dir})
            }
        }
    }
    return out
}

/** A throwaway clone, so a boot that writes (build caches, logs) cannot touch the
 *  corpus. CoW where the filesystem allows, as in boot-skip-corpus. */
function clone(src: string, dest: string): string {
    rmSync(dest, {recursive: true, force: true})
    const cp = spawnSync('cp', ['-a', '--reflink=auto', src, dest], {encoding: 'utf8'})
    if (cp.status !== 0) throw new Error(`cp failed for ${src}: ${cp.stderr}`)
    return dest
}

async function runReal(
    entry: {label: string; dir: string},
    baselineDiscover: DiscoverFn
): Promise<void> {
    const baseCmd = baselineDiscover(entry.dir)
    const treatCmd = discoverBootCommand(entry.dir)
    const differs = label(baseCmd) !== label(treatCmd)
    let baselineBoot: BootClass | '' = ''
    let treatmentBoot: BootClass | '' = ''
    if (differs) {
        // Only here can the two arms produce different runtime behaviour, so this is
        // the only place a boot has to be spent.
        const dir = clone(entry.dir, path.join(work, `${entry.label.replace(/\W+/g, '_')}.boot`))
        try {
            baselineBoot = await bootOutcome(dir, baseCmd)
            treatmentBoot = await bootOutcome(dir, treatCmd)
        } finally {
            rmSync(dir, {recursive: true, force: true})
        }
    }
    results.push({
        label: entry.label,
        dir: entry.dir,
        baselineCmd: label(baseCmd),
        treatmentCmd: label(treatCmd),
        baselineBody: bodyOf(entry.dir, baseCmd),
        baselineBoot,
        treatmentBoot,
        realDevFixture: false
    })
}

async function runFixture(fx: Fixture, baselineDiscover: DiscoverFn): Promise<void> {
    const dir = path.join(work, fx.key)
    buildFixture(fx, dir)
    const baseCmd = baselineDiscover(dir)
    const treatCmd = discoverBootCommand(dir)
    const differs = label(baseCmd) !== label(treatCmd)
    const measure = fx.measureBoot === true || differs
    results.push({
        label: `fixture:${fx.key}`,
        dir,
        baselineCmd: label(baseCmd),
        treatmentCmd: label(treatCmd),
        baselineBody: bodyOf(dir, baseCmd),
        baselineBoot: measure ? await bootOutcome(dir, baseCmd) : '',
        treatmentBoot: measure ? await bootOutcome(dir, treatCmd) : '',
        realDevFixture: fx.realDev === true
    })
}

const isInfra = (t: TreeResult): boolean => INFRA_SHAPE_RE.test(t.baselineBody.trim())
/** The target shape, in the arm's own terms: an infra-orchestration command chosen,
 *  and a boot that observed nothing. */
const targetBaseline = (t: TreeResult): boolean => isInfra(t) && t.baselineBoot === 'skip'
const targetTreatment = (t: TreeResult): boolean =>
    INFRA_SHAPE_RE.test(bodyOfTreatment(t).trim()) && t.treatmentBoot === 'skip'

function bodyOfTreatment(t: TreeResult): string {
    if (t.treatmentCmd === 'none') return ''
    const name = t.treatmentCmd.split(' ')[2] ?? ''
    return scriptsOf(t.dir)[name] ?? ''
}

try {
    const baselineDiscover = await loadBaselineDiscover()
    console.log(`baseline:  discoverBootCommand @ ${BASELINE_REF}`)
    console.log('treatment: working tree')
    console.log(`work dir:  ${work}`)
    console.log('docker/docker-compose shimmed to exit 127 (reproducing run 18\'s sandbox)')

    for (const entry of realTrees()) await runReal(entry, baselineDiscover)
    for (const fx of FIXTURES) await runFixture(fx, baselineDiscover)

    console.log('\nper-tree (label | baseline cmd → boot | treatment cmd → boot):')
    for (const t of results) {
        const b = `${t.baselineCmd}${t.baselineBoot ? ` → ${t.baselineBoot}` : ''}`
        const r = `${t.treatmentCmd}${t.treatmentBoot ? ` → ${t.treatmentBoot}` : ''}`
        console.log(
            `  ${t.label.padEnd(24)} ${b.padEnd(26)} ${r.padEnd(26)}`
                + `${isInfra(t) ? '  <<< infra-orchestration' : ''}`
        )
    }

    const changed = results.filter(t => t.baselineCmd !== t.treatmentCmd)
    const lostABoot = changed.filter(t => t.baselineBoot === 'pass')
    const realDevChanged = results.filter(t => t.realDevFixture && t.baselineCmd !== t.treatmentCmd)
    const realDevBooted = results.filter(t => t.realDevFixture && t.treatmentBoot === 'pass')
    const nonInfraChanged = results.filter(
        t => !isInfra(t) && t.baselineCmd !== t.treatmentCmd && !t.label.includes('watchers-only')
    )

    const detail = (l: TreeResult[]): string | undefined =>
        l.length === 0 ? undefined : l.map(t => `${t.label} (${t.baselineCmd} → ${t.treatmentCmd})`).join('; ')

    const invariants: Invariant[] = [
        {
            label: 'inv-no-boot-lost — no tree OBSERVED to boot lost its command',
            ok: lostABoot.length === 0,
            detail: detail(lostABoot) ?? `${changed.length} changed tree(s) booted, none passed`
        },
        {
            label: 'inv-real-dev-kept — plain server-watch/dev-server scripts still chosen',
            ok: realDevChanged.length === 0 && results.filter(t => t.realDevFixture).length >= 2,
            detail:
                detail(realDevChanged)
                ?? `${results.filter(t => t.realDevFixture).length} real-dev fixture(s) unchanged, `
                    + `${realDevBooted.length} of them observed to BOOT under the treatment`
        },
        {
            label: 'inv-non-infra-unchanged — every other tree resolves identically',
            ok: nonInfraChanged.length === 0,
            detail: detail(nonInfraChanged) ?? `${results.length - changed.length} tree(s) identical`
        }
    ]

    reportAb({
        name: 'boot-command resolution — reject non-launch scripts',
        reps: results.length,
        targetShape:
            'a tree whose chosen boot command is infra-orchestration (INFRA_SHAPE_RE) '
            + 'and whose boot outcome is `skip`',
        baselineHits: results.filter(targetBaseline).length,
        treatmentHits: results.filter(targetTreatment).length,
        invariants
    })
} finally {
    rmSync(BASELINE_FILE, {force: true})
    rmSync(work, {recursive: true, force: true})
}
