#!/usr/bin/env node
// Generates comment-leg.md: one row per source file with its comment debt.
// A "block" is a maximal run of comment-only lines; a trailing comment on a
// code line adds to the comment count but opens no block.
import {execSync} from 'node:child_process'
import {existsSync, readFileSync, writeFileSync} from 'node:fs'

const LEDGER = 'comment-leg.md'

/**
 * The `verified` flags already recorded, keyed by path. A re-run recomputes the
 * counts and must not undo review that has already happened, so the column is
 * read back out of the previous ledger rather than reset to false.
 */
const priorVerified = () => {
	const seen = new Map()
	if (!existsSync(LEDGER)) return seen
	for (const line of readFileSync(LEDGER, 'utf8').split('\n')) {
		const m = /^\|\s*`([^`]+)`\s*\|.*\|\s*(true|false)\s*\|\s*$/.exec(line)
		if (m) seen.set(m[1], m[2] === 'true')
	}
	return seen
}

const files = execSync("git ls-files '*.ts' '*.tsx' '*.mts' '*.cts' '*.js' '*.mjs' '*.cjs'", {encoding: 'utf8'})
	.split('\n')
	.filter(Boolean)
	.filter((f) => !f.includes('__fixtures__/node_modules/'))
	.sort()

const scan = (src) => {
	let comment = 0
	let blocks = 0
	let inBlock = false
	let openRun = false
	// String state carries ACROSS lines: a template literal spans many of them,
	// and `src/remote/ui-script.ts` is one 1241-line backtick string holding the
	// browser client. Resetting this per line reads that string's own `//` lines
	// as TypeScript comments.
	let str = null
	for (const raw of src.split('\n')) {
		let hasCode = false
		let hasComment = false
		let i = 0
		while (i < raw.length) {
			const ch = raw[i]
			const nx = raw[i + 1]
			if (inBlock) {
				hasComment = true
				if (ch === '*' && nx === '/') {
					inBlock = false
					i += 2
				} else i++
				continue
			}
			if (str) {
				if (ch === '\\') {
					i += 2
					continue
				}
				if (ch === str) str = null
				i++
				continue
			}
			if (ch === '/' && nx === '/') {
				hasComment = true
				break
			}
			if (ch === '/' && nx === '*') {
				inBlock = true
				hasComment = true
				i += 2
				continue
			}
			if (ch === '"' || ch === "'" || ch === '`') {
				str = ch
				hasCode = true
				i++
				continue
			}
			if (!/\s/.test(ch)) hasCode = true
			i++
		}
		// A quote can only stay open past a newline if it is a template literal.
		// Anything else unclosed is a scan error, not valid source; drop it so one
		// bad line cannot swallow the rest of the file.
		if (str && str !== '`') str = null
		if (hasComment) comment++
		const ownLine = hasComment && !hasCode
		if (ownLine && !openRun) blocks++
		openRun = ownLine
	}
	return {comment, blocks}
}

const verified = priorVerified()

const rows = files.map((file) => {
	const src = readFileSync(file, 'utf8')
	const lines = src.split('\n').length - (src.endsWith('\n') ? 1 : 0)
	return {file, lines, ...scan(src), verified: verified.get(file) ?? false}
})

const total = rows.reduce(
	(a, r) => ({lines: a.lines + r.lines, comment: a.comment + r.comment, blocks: a.blocks + r.blocks}),
	{lines: 0, comment: 0, blocks: 0},
)

const out = [
	'# Comment ledger',
	'',
	`Generated by \`scripts/comment-ledger.mjs\` on ${new Date().toISOString().slice(0, 10)}.`,
	'',
	`${rows.length} files, ${total.lines} lines, ${total.comment} comment lines, ${total.blocks} comment blocks.`,
	`${rows.filter((r) => r.verified).length} of ${rows.length} files reviewed.`,
	'',
	'A block is a maximal run of comment-only lines. A trailing comment on a code',
	'line counts as a comment line but opens no block.',
	'',
	'| file | lines | comment lines | comment blocks | verified |',
	'| --- | ---: | ---: | ---: | --- |',
	...rows.map((r) => `| \`${r.file}\` | ${r.lines} | ${r.comment} | ${r.blocks} | ${r.verified} |`),
	'',
].join('\n')

writeFileSync(LEDGER, out)
console.log(`${rows.length} files, ${rows.filter((r) => r.verified).length} reviewed -> ${LEDGER}`)
