/**
 * deep-session-endtoend-ab — the only result that counts for nexttask 12.
 *
 *   bun run scripts/deep-session-endtoend-ab.ts      exit 0 PASS · 1 FAIL · 2 ABSTAIN
 *
 * Not a unit test and not a judge-level A/B: the REAL `runFinalIntegrationGate`,
 * twice, against the REAL mx5 tree at 348af86 — the app that shipped with all 33
 * of its client calls addressing `/api/api/…`, dead in any browser.
 *
 *   baseline    the deep-render module as shipped at BASELINE_REF   → must PASS
 *   treatment   the module in the working tree                      → must FAIL
 *
 * Only the deep-render module differs. Both arms run the working tree's final-gate,
 * which reaches the probe through `BootDeps.deepRenderProbe`; the baseline arm is
 * handed the shipped module's `runDeepRenderCheck`, extracted with `git show` into
 * a sibling file so its relative imports resolve. Everything else — boot, render,
 * static checks, ports — is identical, so a difference in `.ok` is this lever and
 * nothing else.
 *
 * Each arm gets its own throwaway worktree: the gate runs `lint --fix`, builds and
 * migrations, so the second arm must never see what the first one did. Nothing is
 * ever written inside ~/hub/mx5.
 *
 * TWO DISCLOSED ENVIRONMENT ADJUSTMENTS, applied identically to both arms inside
 * the worktree (`normalise`). Without them the tree fails two of its OWN commands
 * on THIS box and the baseline cannot pass, which would make the flip unreadable.
 * Neither touches routing, the client, or anything either rule reads:
 *
 *   1. `bun run test` — `defaults to newest first (sort=new)` inserts two listings
 *      back to back and orders by `created_at`, whose resolution is one
 *      millisecond. This box completes both inserts inside one, so the ordering is
 *      a tie and the test fails 5/5. A 5ms wait between the two inserts fixes the
 *      tie. Measured, not assumed: 95/96 before, 96/96 after.
 *   2. `bun run test:ct` — 24 of 44 component tests are screenshot comparisons and
 *      this box does not render pixel-identically to the box that recorded the
 *      baselines (the same adjustment scripts/boot-skip-corpus.ts documents). The
 *      baselines are re-captured in the worktree: 20/44 before, 44/44 after.
 *
 * PASS requires more than the flip. The failure text must NAME the request —
 * a `METHOD /path` plus a status or `text/html` — because a gate that says "the app
 * is broken" without saying which call died is the thing this task replaced.
 */
import {execFileSync, spawnSync} from 'node:child_process'
import {existsSync, readFileSync, rmSync, symlinkSync, writeFileSync} from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import {runFinalIntegrationGate, type FinalGateOutcome} from '../src/task/final-gate'
import {runDeepRenderCheck, type DeepRenderOutcome} from '../src/task/deep-render-check'
import {EXIT_CODE, type Outcome} from './ab-verdict'

/** v0.37.0 — the last release before the request-log lever. */
const BASELINE_REF = process.env.DEEP_SESSION_BASELINE_REF ?? 'c79d9fe'
const REPO = path.resolve(import.meta.dir, '..')
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'deep-render-check.baseline.gen.ts')
const MX5 = path.join(os.homedir(), 'hub', 'mx5')
const MX5_COMMIT = '348af86'
const DB_URL =
    process.env.DEEP_CORPUS_DATABASE_URL
    ?? 'postgres://mx5_dev:mx5_dev_password@localhost:5432/mx5_dscorpus'
const ADMIN_PHONE = '+1234567890'
const ADMIN_PASSWORD = 'corpus-admin-pass'
/** Per-command ceiling, identical for both arms. */
const COMMAND_TIMEOUT_MS = 300_000

type Probe = (url: string, cwd: string) => Promise<DeepRenderOutcome>

const git = (...args: string[]): string =>
    execFileSync('git', ['-C', MX5, ...args], {encoding: 'utf8', stdio: 'pipe'})

async function loadBaselineProbe(): Promise<Probe> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/deep-render-check.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read deep-render-check.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/deep-session-endtoend-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    try {
        const mod: unknown = await import(BASELINE_FILE)
        return (mod as {runDeepRenderCheck: Probe}).runDeepRenderCheck
    } finally {
        // Deleted the instant it is loaded: a stray duplicate module in src/ would
        // be linted, typechecked and shipped by anything that ran next.
        rmSync(BASELINE_FILE, {force: true})
    }
}

/** A fresh worktree of mx5 at the run-20 commit, wired to the throwaway corpus
 *  database, with the host's node_modules linked in (the gate does not install). */
function makeTree(name: string): string {
    const dir = path.join('/tmp', `ds-e2e-${name}`)
    try {
        git('worktree', 'remove', '--force', dir)
    } catch {
        // not a worktree yet
    }
    rmSync(dir, {recursive: true, force: true})
    git('worktree', 'add', '--detach', dir, MX5_COMMIT)
    symlinkSync(path.join(MX5, 'node_modules'), path.join(dir, 'node_modules'))
    writeFileSync(
        path.join(dir, '.env'),
        [
            `DATABASE_URL=${DB_URL}`,
            `ADMIN_PHONE=${ADMIN_PHONE}`,
            `ADMIN_PASSWORD=${ADMIN_PASSWORD}`,
            ''
        ].join('\n')
    )
    return dir
}

/** The two disclosed adjustments, in the worktree only. See the module header. */
function normalise(dir: string): void {
    const file = path.join(dir, 'test/listings.test.ts')
    const src = readFileSync(file, 'utf8')
    const anchor =
        "        await insertListing('l-old', 'user-1', 'Old Listing', 'desc', 1000, 'na', 'oem', 'new')\n"
    if (!src.includes(anchor)) {
        throw new Error(`the created_at-tie anchor is gone from ${file}; re-check the adjustment`)
    }
    writeFileSync(
        file,
        src.replace(anchor, `${anchor}        await new Promise(r => setTimeout(r, 5))\n`)
    )
    const shots = spawnSync('bunx', ['playwright', 'test', '-c', 'playwright-ct.config.ts', '-u'], {
        cwd: dir,
        encoding: 'utf8',
        timeout: 600_000
    })
    console.log(`  ${path.basename(dir)}: CT baselines re-captured (exit ${String(shots.status)})`)
}

const dropTree = (dir: string): void => {
    try {
        git('worktree', 'remove', '--force', dir)
    } catch {
        rmSync(dir, {recursive: true, force: true})
        try {
            git('worktree', 'prune')
        } catch {
            // nothing to prune
        }
    }
}

async function arm(name: string, probe: Probe): Promise<FinalGateOutcome> {
    const dir = makeTree(name)
    try {
        normalise(dir)
        const started = Date.now()
        const out = await runFinalIntegrationGate(dir, COMMAND_TIMEOUT_MS, 15_000, {
            deepRenderProbe: url => probe(url, dir)
        })
        console.log(
            `  ${name.padEnd(9)} gate ${out.ok ? 'PASS' : 'FAIL'} in `
            + `${((Date.now() - started) / 1000).toFixed(0)}s`
        )
        return out
    } finally {
        dropTree(dir)
    }
}

if (!existsSync(MX5)) {
    console.error(`ABSTAIN — ${MX5} is not on this box; there is no served app to judge.`)
    process.exit(EXIT_CODE.ABSTAIN)
}

console.log(`=== the final gate against mx5@${MX5_COMMIT}, twice (baseline ${BASELINE_REF} vs working tree)\n`)
const baselineProbe = await loadBaselineProbe()
const baseline = await arm('baseline', baselineProbe)
const treatment = await arm('treatment', (url, cwd) => runDeepRenderCheck(url, cwd))

/** `METHOD /path` plus a status or a mime type — the request, named. */
const NAMES_A_REQUEST = /`[A-Z]+ \/\S*` → (?:\d{3}|.*text\/html)/
const named = NAMES_A_REQUEST.exec(treatment.reason)

const outcome: Outcome =
    baseline.ok && !treatment.ok && named !== null ? 'PASS'
    : baseline.ok === treatment.ok ? 'FAIL'
    : 'FAIL'

console.log('')
console.log('=== VERDICT: the shipped gate vs the request-log gate, end to end')
console.log(`  baseline  .ok = ${String(baseline.ok)}   (must be true — the defect shipped)`)
console.log(`  treatment .ok = ${String(treatment.ok)}  (must be false)`)
console.log(`  failure names a request: ${named === null ? 'NO' : `yes — ${named[0]}`}`)
console.log('')
if (!baseline.ok) {
    console.log('BASELINE FAILED. The gate as shipped does not pass this tree, so the flip')
    console.log('this harness measures would not be about the lever. Baseline reason:')
    console.log(baseline.reason)
}
if (outcome === 'PASS') {
    console.log('PASS — the app that shipped is now a gate FAILURE, and the failure says which call died:')
    console.log(treatment.reason.split('\n').find(l => NAMES_A_REQUEST.test(l)) ?? treatment.reason)
} else {
    console.log('FAIL — treatment reason:')
    console.log(treatment.reason)
}
process.exit(EXIT_CODE[outcome])
