/**
 * deep-session-judge-ab — does judging the whole request log, instead of two
 * integers over it, turn the broken sessions into FAILs without touching the
 * healthy ones?
 *
 *   bun run scripts/deep-session-judge-ab.ts
 *   exit 0 PASS · 1 FAIL · 2 ABSTAIN
 *
 * Both arms are the REAL `judgeDeepSession` over the SAME nine recorded sessions
 * (scripts/fixtures/deep-sessions.json, built by deep-session-corpus.ts from real
 * browser sessions against a real server). The baseline is the module as shipped at
 * BASELINE_REF, extracted with `git show` into a sibling file so its relative
 * imports resolve; the treatment is the working tree. No browser, no server, no
 * model — the fixture IS the measurement, so this is deterministic and re-runnable.
 *
 * BASELINE_REF is PINNED. Once the lever lands, HEAD contains it and a re-run would
 * compare the lever against itself.
 *
 * Pre-registered metric: per entry, `outcome === expected`. The target shape is a
 * session the corpus calls broken that the judge does not call broken.
 *
 * ABSTAIN: no entry carries a 404/405/501 XHR and none carries an html-answered
 * XHR — the corpus cannot exercise either rule, so a clean treatment column would
 * mean nothing.
 */
import {spawnSync} from 'node:child_process'
import {readFileSync, rmSync, writeFileSync} from 'node:fs'
import * as path from 'node:path'
import {
    judgeDeepSession,
    type DeepRenderOutcome,
    type DeepSessionFacts,
    type SessionRequest
} from '../src/task/deep-render-check'
import {EXIT_CODE, reportAb, type Invariant} from './ab-verdict'

/** v0.37.0 — the last release before the request-log lever. */
const BASELINE_REF = process.env.DEEP_SESSION_BASELINE_REF ?? 'c79d9fe'
const REPO = path.join(import.meta.dir, '..')
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'deep-render-check.baseline.gen.ts')
const CORPUS = path.join(import.meta.dir, 'fixtures', 'deep-sessions.json')
/** The three entries whose verdict the lever must not touch at all. */
const UNTOUCHED = ['mut-fixed', 'mut-badpass', 'mut-db-down']

interface CorpusEntry {
    name: string
    expected: 'pass' | 'fail' | 'skip'
    why: string
    shippedOutcome: string
    requestsRecorded: number
    facts: DeepSessionFacts
}

type Judge = (f: DeepSessionFacts) => DeepRenderOutcome

/** The shipped judge, materialised next to its own dependencies so `./x.js`
 *  imports resolve exactly as they do for the real one. */
async function loadBaselineJudge(): Promise<Judge> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/deep-render-check.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read deep-render-check.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/deep-session-judge-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    try {
        const mod: unknown = await import(BASELINE_FILE)
        return (mod as {judgeDeepSession: Judge}).judgeDeepSession
    } finally {
        rmSync(BASELINE_FILE, {force: true})
    }
}

const corpus = JSON.parse(readFileSync(CORPUS, 'utf8')) as CorpusEntry[]
if (corpus.length === 0) {
    console.error(`no corpus at ${CORPUS} — run scripts/deep-session-corpus.ts first`)
    process.exit(EXIT_CODE.ABSTAIN)
}

const requests = (e: CorpusEntry): SessionRequest[] => e.facts.sessionRequests ?? []
const hasMissingRoute = corpus.some(e =>
    requests(e).some(r => r.initiator === 'xhr' && [404, 405, 501].includes(r.status ?? 0))
)
const hasHtmlXhr = corpus.some(e =>
    requests(e).some(r => r.initiator === 'xhr' && (r.mimeType ?? '').startsWith('text/html'))
)
if (!hasMissingRoute && !hasHtmlXhr) {
    console.error(
        'ABSTAIN — no corpus entry carries a 404/405/501 XHR and none carries an '
        + 'html-answered XHR. Neither rule can fire, so this corpus cannot test the '
        + 'lever. Return to scripts/deep-session-corpus.ts.'
    )
    process.exit(EXIT_CODE.ABSTAIN)
}

const baseline = await loadBaselineJudge()
const rows = corpus.map(e => {
    const b = baseline(e.facts)
    const t = judgeDeepSession(e.facts)
    return {
        name: e.name,
        expected: e.expected,
        baseline: b.outcome,
        treatment: t.outcome,
        treatmentText: t.outcome === 'skip' ? t.note : t.detail
    }
})

console.log(`=== nine recorded sessions, judged twice (baseline ${BASELINE_REF} vs working tree)\n`)
for (const r of rows) {
    const mark = r.treatment === r.expected ? ' ' : '✗'
    console.log(
        `${mark} ${r.name.padEnd(24)} expected ${r.expected.padEnd(5)} `
        + `baseline ${r.baseline.padEnd(5)} treatment ${r.treatment}`
    )
    if (r.treatment === 'fail') console.log(`      ${r.treatmentText.split('\n')[0].slice(0, 160)}`)
}

const untouched = rows.filter(r => UNTOUCHED.includes(r.name))
const invariants: Invariant[] = [
    {
        label: 'the healthy, the rejected password and the dead database judge exactly as before',
        ok: untouched.every(r => r.baseline === r.treatment),
        detail: untouched.map(r => `${r.name} ${r.baseline}→${r.treatment}`).join(', ')
    },
    {
        label: 'no session is failed for a reason the log does not name',
        ok: rows
            .filter(r => r.treatment === 'fail')
            .every(r => /`[A-Z]+ \/\S*` → /.test(r.treatmentText) || r.baseline === 'fail'),
        detail: 'every new FAIL text carries a `METHOD /path` → status'
    },
    {
        label: 'both rules are exercised by the corpus',
        ok: hasMissingRoute && hasHtmlXhr,
        detail: `missing-route XHR: ${String(hasMissingRoute)}, html-answered XHR: ${String(hasHtmlXhr)}`
    }
]

process.exit(
    EXIT_CODE[
        reportAb({
            name: 'deep-session judge — whole request log vs two integers',
            reps: rows.length,
            targetShape: 'a recorded session the corpus calls broken that the judge does not call broken',
            baselineHits: rows.filter(r => r.baseline !== r.expected).length,
            treatmentHits: rows.filter(r => r.treatment !== r.expected).length,
            invariants
        })
    ]
)
