/**
 * A/B-1 for nexttask 10 — does the env-template closure check add the mx5 run-19
 * finding to the final gate's ranked failure list without changing the verdict of
 * anything else?
 *
 * Deterministic: no model, no PI_BIN, no llama-server, no network. Both arms are
 * the REAL `runFinalIntegrationGate` — the baseline is the module as shipped at
 * BASELINE_REF, extracted with `git show` into a sibling file so its relative
 * imports still resolve; the treatment is the working tree. BASELINE_REF is
 * PINNED, not `HEAD`: once the lever lands, `HEAD` contains it and a re-run would
 * compare the lever against itself and report a triumphant zero.
 *
 * The gate RUNS COMMANDS and its statics WRITE (`prettier --write`, `eslint
 * --fix`), so every tree is materialised into a throwaway clone per ARM — the two
 * arms never share a tree, and the corpus is never touched. The docker shim from
 * the boot-skip harness is reused so a `dev` script that starts containers cannot
 * start anything on this box.
 *
 * Pre-registered metric: the gate VERDICT and its RANKED FAILURE LIST per tree.
 *
 *     PASS      mx5@dfbdd6f gains a rank-0 failure naming ADMIN_PHONE and
 *               ADMIN_PASSWORD with their read sites, AND every invariant
 *               holds.                                                    exit 0
 *     FAIL      it does not, or any invariant breaks.                     exit 1
 *     ABSTAIN   no tree in the corpus carries a template.                 exit 2
 *
 * Invariants (nexttask 10, verbatim):
 *   inv-no-template-no-finding    a tree with no tracked env template is
 *                                 byte-identical to baseline (ENOENT = pass).
 *   inv-declared-silent           a DECLARED variable never produces a finding,
 *                                 however it is read. The check is one-directional.
 *   inv-untracked-invisible       reads in untracked/gitignored files produce
 *                                 nothing — and an untracked template declares
 *                                 nothing.
 *   inv-no-verdict-flip-on-clean  a tree that PASSes baseline with no missing var
 *                                 still PASSes. dace-pro is the fixture.
 *   inv-idempotent                scanning twice yields the same findings.
 *
 * A difference between arms that is NOT an env-closure line is reported as
 * SUITE FLAKE, loudly, and breaks the identity invariants — two clones of one
 * tree running the same commands should produce the same list, and if they do
 * not, this harness must say so rather than average it away.
 *
 *     bun run scripts/env-template-closure-ab.ts
 */
import {spawnSync} from 'node:child_process'
import {mkdirSync, rmSync, writeFileSync} from 'node:fs'
import * as path from 'node:path'
import type {FinalGateOutcome, FinalGateOptions} from '../src/task/final-gate.js'
import {scanEnvTemplateClosure} from '../src/task/env-template-closure.js'
import {report, type Invariant, type Outcome} from './ab-verdict.js'
import {HUB, REPO, makeWorkRoot, installDockerlessShim} from './boot-skip-corpus.js'

const BASELINE_REF = process.env.ENV_CLOSURE_BASELINE_REF ?? '54ed4ad'
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'final-gate.baseline.gen.ts')
/** Every gate command gets the same ceiling in both arms, so it can shift a
 *  tree's verdict but never the DIFFERENCE the A/B measures. */
const GATE_TIMEOUT_MS = 600_000

type GateFn = (cwd: string, opts?: FinalGateOptions) => Promise<FinalGateOutcome>

async function loadBaselineGate(): Promise<GateFn> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/final-gate.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read final-gate.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/env-template-closure-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    try {
        const mod = (await import(BASELINE_FILE)) as {runFinalIntegrationGate: GateFn}
        return mod.runFinalIntegrationGate
    } finally {
        rmSync(BASELINE_FILE, {force: true})
    }
}

// ── corpus ────────────────────────────────────────────────────────────────────

interface Tree {
    label: string
    /** Materialise the tree at `dest`. Runs once per ARM. */
    build: (dest: string) => void
    /** Variables the treatment is EXPECTED to name, in order. */
    expect: string[]
    /** What this tree is here to prove. */
    note: string
    lead?: true
    /** Per-tree ceiling; suites that are LLM/network harnesses get a short one. */
    timeoutMs?: number
}

function gitInit(dir: string): void {
    spawnSync('git', ['init', '-q'], {cwd: dir})
    spawnSync('git', ['add', '-A'], {cwd: dir})
    spawnSync('git', ['-c', 'user.email=a@b', '-c', 'user.name=a', 'commit', '-qm', 'fixture'], {
        cwd: dir
    })
}

function writeFiles(dir: string, files: Record<string, string>): void {
    for (const [rel, body] of Object.entries(files)) {
        mkdirSync(path.dirname(path.join(dir, rel)), {recursive: true})
        writeFileSync(path.join(dir, rel), body)
    }
}

/** A clone of a real tree (CoW where the filesystem allows). */
function clone(source: string, dest: string, after?: (dest: string) => void): void {
    rmSync(dest, {recursive: true, force: true})
    mkdirSync(path.dirname(dest), {recursive: true})
    const cp = spawnSync('cp', ['-a', '--reflink=auto', source, dest], {encoding: 'utf8'})
    if (cp.status !== 0) throw new Error(`cp failed for ${source}: ${cp.stderr}`)
    after?.(dest)
}

const PY_APP = 'import os\ndb = os.environ["DATABASE_URL"]\nadmin = os.environ["ADMIN_PHONE"]\n'

const CORPUS: Tree[] = [
    {
        label: 'mx5@dfbdd6f (run 19, as shipped)',
        lead: true,
        expect: ['ADMIN_PHONE', 'ADMIN_PASSWORD'],
        // `.env` is REMOVED: it is gitignored (nexttask 4), so it does not exist in
        // the tree anyone clones — and it is the file the run-19 autofix wrote the
        // two variables into. Leaving the local copy in place would measure this
        // box's leftovers, not the artifact that shipped. Disclosed, not silent.
        build: dest => clone(path.join(HUB, 'mx5'), dest, d => rmSync(path.join(d, '.env'), {force: true})),
        note: 'THE LEAD — seed.ts requires ADMIN_PHONE/ADMIN_PASSWORD, .env.example declares neither'
    },
    {
        label: 'dace-pro (human-authored, template complete)',
        expect: [],
        build: dest => clone(path.join(HUB, 'dace-pro'), dest),
        timeoutMs: 300_000,
        note: 'inv-no-verdict-flip-on-clean — 13 declared / 9 required, zero missing'
    },
    {
        label: 'pi-task (self, no template)',
        expect: [],
        build: dest => clone(REPO, dest),
        timeoutMs: 300_000,
        note: 'inv-no-template-no-finding on a REAL tree with many env reads'
    },
    {
        label: 'fixture:missing-python',
        expect: ['ADMIN_PHONE'],
        build: dest => {
            writeFiles(dest, {
                '.env.example': 'DATABASE_URL=postgres://x\n',
                'app/main.py': PY_APP,
                'package.json': `${JSON.stringify({name: 'fx-py', private: true, scripts: {test: 'echo ok'}}, null, 4)}\n`
            })
            gitInit(dest)
        },
        note: 'the same defect in a NON-JS ecosystem — the rule is not npm-shaped'
    },
    {
        label: 'fixture:declared',
        expect: [],
        build: dest => {
            writeFiles(dest, {
                '.env.example': 'DATABASE_URL=postgres://x\nADMIN_PHONE=\n',
                'app/main.py': PY_APP,
                'package.json': `${JSON.stringify({name: 'fx-declared', private: true, scripts: {test: 'echo ok'}}, null, 4)}\n`
            })
            gitInit(dest)
        },
        note: 'inv-declared-silent — a bare `ADMIN_PHONE=` line is a declaration'
    },
    {
        label: 'fixture:no-template',
        expect: [],
        build: dest => {
            writeFiles(dest, {
                'app/main.py': PY_APP,
                'package.json': `${JSON.stringify({name: 'fx-none', private: true, scripts: {test: 'echo ok'}}, null, 4)}\n`
            })
            gitInit(dest)
        },
        note: 'inv-no-template-no-finding — never invent a file the project chose not to have'
    },
    {
        label: 'fixture:untracked',
        expect: [],
        build: dest => {
            writeFiles(dest, {
                '.env.example': 'DATABASE_URL=postgres://x\n',
                '.gitignore': 'scratch.py\n.env\n',
                'app/main.py': 'import os\ndb = os.environ["DATABASE_URL"]\n',
                'package.json': `${JSON.stringify({name: 'fx-untracked', private: true, scripts: {test: 'echo ok'}}, null, 4)}\n`
            })
            gitInit(dest)
            // AFTER the commit: a gitignored source requiring a var, an untracked
            // source requiring another, and an untracked template that declares
            // nothing. None of the three may reach the check.
            writeFiles(dest, {
                'scratch.py': 'import os\nk = os.environ["IGNORED_SECRET"]\n',
                'untracked.py': 'import os\nk = os.environ["UNTRACKED_SECRET"]\n',
                '.env.sample': '# untracked template\n',
                '.env': 'DATABASE_URL=postgres://local\n'
            })
        },
        note: 'inv-untracked-invisible — gitignored + untracked reads and templates are silent'
    }
]

// ── run ───────────────────────────────────────────────────────────────────────

const ENV_LINE_RE = /^env closure: /

/**
 * Failure texts quote command output, and that output carries two things that
 * cannot be equal across two clones: the tree's ABSOLUTE PATH (each arm gets its
 * own) and the suite's own ELAPSED TIME (`[90.00ms]` vs `[97.00ms]`). The first
 * run of this harness reported three identical failures as appeared/disappeared
 * for the path alone, and the second still differed on the milliseconds. Both are
 * normalised out — the full path, its basename (failure text is tail-truncated,
 * so a fragment can start mid-path), and any duration literal. Nothing else is
 * rewritten: a real difference in what failed still shows.
 */
function normalise(dest: string, s: string): string {
    return s
        .split(dest)
        .join('<TREE>')
        .split(path.basename(dest))
        .join('<TREE>')
        .replace(/\[\d+(?:\.\d+)?\s*m?s\]/g, '[<T>]')
        .replace(/\b\d+(?:\.\d+)?\s*ms\b/g, '<T>ms')
}

const listOf = (o: FinalGateOutcome): string[] => o.failures ?? (o.ok ? [] : [o.reason])

interface ArmResult {
    ok: boolean
    failures: string[]
}

/**
 * ONE snapshot per tree, copied into each arm — never two independent
 * materialisations. The second run of this harness cloned `pi-task (self)` for
 * the baseline arm, ran it, and cloned again for the treatment arm minutes
 * later, by which time the source tree (this repo, under active edit) had gained
 * a file that did not typecheck: the treatment "grew" a lint failure the lever
 * had nothing to do with. A live tree drifts; the A/B must not sample it twice.
 */
function snapshotOf(tree: Tree, work: string): string {
    const snap = path.join(work, `${slug(tree.label)}-snapshot`)
    tree.build(snap)
    return snap
}

async function runArm(gate: GateFn, snap: string, tree: Tree, dest: string): Promise<ArmResult> {
    rmSync(dest, {recursive: true, force: true})
    const cp = spawnSync('cp', ['-a', '--reflink=auto', `${snap}/.`, dest], {encoding: 'utf8'})
    if (cp.status !== 0) throw new Error(`cp of snapshot failed for ${tree.label}: ${cp.stderr}`)
    const o = await gate(dest, {timeoutMs: tree.timeoutMs ?? GATE_TIMEOUT_MS})
    return {ok: o.ok, failures: listOf(o).map(f => normalise(dest, f))}
}

async function main(): Promise<void> {
    const t0 = Date.now()
    const baselineGate = await loadBaselineGate()
    const {runFinalIntegrationGate: treatmentGate} = await import('../src/task/final-gate.js')
    const work = makeWorkRoot('env-closure-ab')
    installDockerlessShim(work)

    const rows: string[] = []
    const flakes: string[] = []
    let leadPass = false
    let templatesSeen = 0
    let declaredSilent = true
    let untrackedInvisible = true
    let noTemplateIdentical = true
    let noFlipOnClean = true
    let idempotent = true

    for (const tree of CORPUS) {
        const snap = snapshotOf(tree, work)
        // EQUAL-LENGTH arm directories. Failure text is tail-truncated by the gate
        // (last ~300 chars), so a longer directory name shifts the truncation
        // window: with `-baseline`/`-treatment` the two arms' quoted output began
        // one character apart and stayed unequal even after the path itself was
        // normalised away. Same length ⇒ same window ⇒ a difference means a
        // difference.
        const base = path.join(work, `${slug(tree.label)}-arm-a`)
        const treat = path.join(work, `${slug(tree.label)}-arm-b`)
        const b = await runArm(baselineGate, snap, tree, base)
        const t = await runArm(treatmentGate, snap, tree, treat)
        rmSync(snap, {recursive: true, force: true})
        const closure = scanEnvTemplateClosure(treat)
        if (closure.templates.length > 0) templatesSeen++
        // Idempotence on the tree the treatment actually saw.
        const again = scanEnvTemplateClosure(treat)
        const key = (c: typeof closure): string =>
            c.missing.map(m => `${m.name}@${m.file}:${m.line}`).join('|')
        if (key(closure) !== key(again)) idempotent = false

        const added = t.failures.filter(f => !b.failures.includes(f))
        const removed = b.failures.filter(f => !t.failures.includes(f))
        const envAdded = added.filter(f => ENV_LINE_RE.test(f))
        const otherAdded = added.filter(f => !ENV_LINE_RE.test(f))
        if (otherAdded.length > 0 || removed.length > 0) {
            flakes.push(
                `${tree.label}: ${otherAdded.length} non-env line(s) appeared, ${removed.length} disappeared`
                    + `\n    + ${otherAdded.join('\n    + ')}${removed.length ? `\n    - ${removed.join('\n    - ')}` : ''}`
            )
        }
        const namesFound = tree.expect.filter(n => envAdded.some(f => f.includes(n)))
        const rankZeroFirst = t.failures.length <= 1 || ENV_LINE_RE.test(t.failures[0]) || envAdded.length === 0

        rows.push(
            `${tree.label}\n`
                + `    ${tree.note}\n`
                + `    baseline  ${b.ok ? 'PASS' : 'FAIL'} (${b.failures.length} failures)\n`
                + `    treatment ${t.ok ? 'PASS' : 'FAIL'} (${t.failures.length} failures)\n`
                + `    env findings added: ${envAdded.length}`
                + (envAdded.length > 0 ? `\n      ${envAdded.join('\n      ')}` : '')
        )

        if (tree.lead) {
            leadPass =
                namesFound.length === tree.expect.length
                && envAdded.length === tree.expect.length
                && !t.ok
                && rankZeroFirst
                && otherAdded.length === 0
                && removed.length === 0
        }
        if (tree.expect.length === 0) {
            // Every non-lead tree must be byte-identical across arms.
            const identical =
                b.ok === t.ok
                && b.failures.length === t.failures.length
                && b.failures.every((f, i) => f === t.failures[i])
            if (closure.templates.length === 0 && !identical) noTemplateIdentical = false
            if (closure.templates.length > 0 && envAdded.length > 0) declaredSilent = false
            if (tree.label.includes('untracked') && envAdded.length > 0) untrackedInvisible = false
            if (b.ok && !t.ok) noFlipOnClean = false
        }
        if (tree.expect.length > 0 && envAdded.length !== tree.expect.length) {
            // A positive tree that under- or over-fires is a lead-level failure too.
            if (!tree.lead) declaredSilent = declaredSilent && envAdded.length >= tree.expect.length
        }
    }

    const invariants: Invariant[] = [
        {
            label: 'inv-no-template-no-finding',
            ok: noTemplateIdentical,
            detail: 'trees with no tracked template are byte-identical to baseline'
        },
        {
            label: 'inv-declared-silent',
            ok: declaredSilent,
            detail: 'a declared variable never produces a finding'
        },
        {
            label: 'inv-untracked-invisible',
            ok: untrackedInvisible,
            detail: 'gitignored/untracked reads and templates are silent'
        },
        {
            label: 'inv-no-verdict-flip-on-clean',
            ok: noFlipOnClean,
            detail: 'no clean tree flipped PASS → FAIL'
        },
        {label: 'inv-idempotent', ok: idempotent, detail: 'two scans, same findings'},
        {
            label: 'inv-no-suite-flake',
            ok: flakes.length === 0,
            detail:
                flakes.length === 0 ?
                    'no non-env difference between arms'
                :   `${flakes.length} tree(s) differed outside the env lines`
        }
    ]

    const outcome: Outcome =
        templatesSeen === 0 ? 'ABSTAIN'
        : leadPass && invariants.every(i => i.ok) ? 'PASS'
        : 'FAIL'

    const lines = [
        '# A/B-1 — env-template closure (nexttask 10)',
        `baseline ref ${BASELINE_REF}   trees ${CORPUS.length}   carrying a template ${templatesSeen}`,
        '',
        ...rows,
        ...(flakes.length > 0 ?
            ['', '## SUITE FLAKE (non-env differences between arms)', '', ...flakes.map(f => `  ${f}`)]
        :   []),
        '',
        '## invariants',
        '',
        ...invariants.map(i => `  invariant ${i.ok ? 'HOLDS ' : 'BROKEN'} ${i.label} — ${i.detail}`),
        '',
        `${outcome} — the lead ${leadPass ? 'gained both findings at rank 0' : 'did NOT gain both findings at rank 0'}`
            + ` (${((Date.now() - t0) / 1000 / 60).toFixed(1)} min)`,
        `work root ${work}`
    ]
    report({outcome, lines})
}

function slug(s: string): string {
    return s.replace(/[^a-z0-9]+/gi, '-').slice(0, 40)
}

await main()
