/**
 * A/B for nexttask 3 — does scanning the HTML a build script GENERATES catch the
 * mx5 run-18 shape (the final-gate autofix closed one dangling reference by
 * authoring two new ones, `/app.css` and `/main.js`, one indirection deeper)
 * without inventing a single new finding anywhere else?
 *
 * Deterministic: no model, no PI_BIN, no llama-server, no network. Both arms are
 * the REAL `findDanglingArtifacts` — the baseline is the module as shipped at
 * BASELINE_REF, extracted with `git show` into a sibling file so its relative
 * imports still resolve; the treatment is the working tree. Both run in ONE
 * process over ONE corpus. The scan is read-only, so unlike the boot-skip
 * harness no arm can mutate a tree the other one sees.
 *
 * BASELINE_REF is PINNED, not `HEAD`. Once the lever lands, `HEAD` contains it
 * and a re-run would compare the lever against itself and report a triumphant
 * ABSTAIN-shaped zero. The pin is the pre-lever release.
 *
 * Pre-registered metric: the SET of dangling findings per tree, compared as sets
 * (not counts), so a lost true positive is as visible as a new false positive.
 *
 *     PASS     baseline misses the /app.css finding on mx5@a9c6145;
 *              treatment reports it; AND every invariant holds.   exit 0
 *     FAIL     treatment misses it, or any invariant breaks.      exit 1
 *     ABSTAIN  the mx5 evidence tree is unavailable.              exit 2
 *
 * Run: bun run scripts/html-asset-closure-ab.ts
 */
import {spawnSync} from 'node:child_process'
import {mkdirSync, mkdtempSync, rmSync, writeFileSync} from 'node:fs'
import {tmpdir} from 'node:os'
import * as path from 'node:path'
import {
    findDanglingArtifacts,
    danglingGateFailureText,
    type DanglingRef
} from '../src/task/artifact-closure.js'
import {report, reportAb, type Invariant} from './ab-verdict.js'
import {buildCorpus, MX5_COMMITS, REPO, type CorpusTree} from './html-asset-closure-corpus.js'

const BASELINE_REF = process.env.HTML_CLOSURE_BASELINE_REF ?? '98d8c10'
const BASELINE_FILE = path.join(REPO, 'src', 'task', 'artifact-closure.baseline.gen.ts')

type ScanFn = (cwd: string) => DanglingRef[]

/** The shipped module, materialised next to its own dependencies so `./x.js`
 *  imports resolve exactly as they do for the real one — then deleted at once,
 *  because pi-task itself is in the corpus and a scan taken while the file
 *  existed would be scanning a stray duplicate of the module under test. */
async function loadBaselineScan(): Promise<ScanFn> {
    const show = spawnSync('git', ['show', `${BASELINE_REF}:src/task/artifact-closure.ts`], {
        cwd: REPO,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024
    })
    if (show.status !== 0 || !show.stdout) {
        throw new Error(`cannot read artifact-closure.ts at ${BASELINE_REF}: ${show.stderr}`)
    }
    writeFileSync(
        BASELINE_FILE,
        `// GENERATED by scripts/html-asset-closure-ab.ts from ${BASELINE_REF} — do not edit, do not commit.\n`
            + show.stdout
    )
    try {
        const mod = (await import(BASELINE_FILE)) as {findDanglingArtifacts: ScanFn}
        return mod.findDanglingArtifacts
    } finally {
        rmSync(BASELINE_FILE, {force: true})
    }
}

// --------------------------------------------------------------------------
// Fixtures: the three invariants nexttask 3 pins, plus the negative control the
// dev-only rule needs to prove it DISCRIMINATES rather than always firing.
// --------------------------------------------------------------------------

const BUILD_TS = (htmlConst: string): string =>
    [
        "await Bun.build({entrypoints: ['src/main.ts'], outdir: 'dist'})",
        '',
        htmlConst,
        '',
        "Bun.write('dist/index.html', html)",
        ''
    ].join('\n')

interface Fixture {
    key: string
    /** Findings expected in BOTH arms are 'baseline'; treatment-only in 'added'. */
    expectTreatment: string[]
    build: (dir: string) => void
}

function writeTree(dir: string, files: Record<string, string>): void {
    for (const [rel, body] of Object.entries(files)) {
        const abs = path.join(dir, rel)
        mkdirSync(path.dirname(abs), {recursive: true})
        writeFileSync(abs, body)
    }
}

const FIXTURES: Fixture[] = [
    {
        key: 'inv-scheme-urls-ignored',
        expectTreatment: [],
        build: dir =>
            writeTree(dir, {
                'package.json': JSON.stringify({scripts: {build: 'bun run build.ts'}}),
                'src/main.ts': 'export const x = 1\n',
                'build.ts': BUILD_TS(
                    'const html = `<!doctype html><html><head>'
                        + '<script src="https://cdn.example/x.js"></script>'
                        + '<link rel="stylesheet" href="//cdn.example/x.css" />'
                        + '<link rel="icon" href="data:image/png;base64,AAAA" />'
                        + '</head><body><a href="/about">about</a>'
                        + '<script type="module" src="/main.js"></script></body></html>`'
                )
            })
    },
    {
        key: 'inv-non-build-html-ignored',
        expectTreatment: [],
        build: dir =>
            writeTree(dir, {
                'package.json': JSON.stringify({scripts: {build: 'bun run build.ts'}}),
                'src/main.ts': 'export const x = 1\n',
                // The aiz-server mailTemplate.ts shape: an HTML literal that is an
                // EMAIL BODY, never written into a build output. Its assets must
                // stay invisible — including a root-relative one, which is the
                // reference that would actually resolve if the gate were wrong.
                'src/mail-template.ts':
                    'export default `<!doctype html><html><body>'
                    + '<img src="cid:logo" alt="logo" />'
                    + '<link rel="stylesheet" href="/brand.css" />'
                    + '<img src="/pixel.png" /></body></html>`\n',
                'build.ts':
                    "await Bun.build({entrypoints: ['src/main.ts'], outdir: 'dist'})\n"
            })
    },
    {
        key: 'inv-dev-only-is-dangling',
        expectTreatment: ['dist/site.css'],
        build: dir =>
            writeTree(dir, {
                'package.json': JSON.stringify({
                    scripts: {
                        build: 'bun run build.ts',
                        // The ONLY producer of dist/site.css — a watch script the
                        // production build never invokes (the mx5 dev:css shape).
                        'dev:css': 'bunx @tailwindcss/cli -i src/app.css -o dist/site.css --watch'
                    }
                }),
                'src/main.ts': 'export const x = 1\n',
                'src/app.css': '/* source */\n',
                'build.ts': BUILD_TS(
                    'const html = `<!doctype html><html><head>'
                        + '<link rel="stylesheet" href="/site.css" />'
                        + '</head><body><script type="module" src="/main.js"></script>'
                        + '</body></html>`'
                )
            })
    },
    {
        key: 'ctl-production-producer-closes',
        expectTreatment: [],
        build: dir =>
            writeTree(dir, {
                'package.json': JSON.stringify({
                    scripts: {
                        // Same tree as above with ONE difference: the CSS producer
                        // is a real build step (no --watch, not named dev*). If the
                        // dev rule fired on this too it would be a blanket "any
                        // generated asset dangles" rule, not the pre-registered one.
                        build: 'bun run build.ts && bun run build:css',
                        'build:css': 'bunx @tailwindcss/cli -i src/app.css -o dist/site.css'
                    }
                }),
                'src/main.ts': 'export const x = 1\n',
                'src/app.css': '/* source */\n',
                'build.ts': BUILD_TS(
                    'const html = `<!doctype html><html><head>'
                        + '<link rel="stylesheet" href="/site.css" />'
                        + '</head><body><script type="module" src="/main.js"></script>'
                        + '</body></html>`'
                )
            })
    }
]

// --------------------------------------------------------------------------

const key = (d: DanglingRef): string => `${d.referencer} → ${d.path}`
const setOf = (ds: DanglingRef[]): string[] => ds.map(key).sort()
const eq = (a: string[], b: string[]): boolean => JSON.stringify(a) === JSON.stringify(b)

interface Scan {
    label: string
    baseline: string[]
    treatment: string[]
    treatmentFull: DanglingRef[]
}

async function main(): Promise<void> {
    const baselineScan = await loadBaselineScan()
    const corpus = buildCorpus()
    const target = corpus.find(t => t.label.includes(MX5_COMMITS.postAutofix))
    if (target === undefined || target.dir === null) {
        report({
            outcome: 'ABSTAIN',
            lines: [
                '',
                '=== VERDICT: html-asset-closure ===',
                `  the mx5 evidence tree (@${MX5_COMMITS.postAutofix}) is unavailable on this box;`,
                '  the run-18 shape cannot be reproduced, so this run proves nothing.'
            ]
        })
        return
    }

    const scans: Scan[] = []
    const work = mkdtempSync(path.join(tmpdir(), 'html-closure-fx-'))
    try {
        const trees: CorpusTree[] = [...corpus]
        for (const f of FIXTURES) {
            const dir = path.join(work, f.key)
            mkdirSync(dir, {recursive: true})
            f.build(dir)
            trees.push({label: `fixture:${f.key}`, dir, expectation: f.expectTreatment.join(',')})
        }
        for (const t of trees) {
            if (t.dir === null) continue
            scans.push({
                label: t.label,
                baseline: setOf(baselineScan(t.dir)),
                treatment: setOf(findDanglingArtifacts(t.dir)),
                treatmentFull: findDanglingArtifacts(t.dir)
            })
        }
    } finally {
        rmSync(work, {recursive: true, force: true})
    }

    console.log(`baseline: artifact-closure.ts @ ${BASELINE_REF}`)
    for (const s of scans) {
        const same = eq(s.baseline, s.treatment)
        console.log(`\n${s.label}${same ? '  (unchanged)' : '  *** CHANGED ***'}`)
        console.log(`  baseline : ${s.baseline.length === 0 ? '(none)' : s.baseline.join(' | ')}`)
        console.log(`  treatment: ${s.treatment.length === 0 ? '(none)' : s.treatment.join(' | ')}`)
        if (!same) for (const d of s.treatmentFull) console.log(`    - ${danglingGateFailureText(d)}`)
    }

    const byLabel = (frag: string): Scan | undefined => scans.find(s => s.label.includes(frag))
    const APP_CSS = 'build.ts → dist/app.css'
    const t = byLabel(MX5_COMMITS.postAutofix)

    // Target shape: the run-18 dangle goes UNREPORTED. Baseline ships it, the
    // treatment must not. One deterministic tree = the whole population here;
    // there is no sampling noise in a static scan.
    const baselineHits = t !== undefined && !t.baseline.includes(APP_CSS) ? 1 : 0
    const treatmentHits = t !== undefined && !t.treatment.includes(APP_CSS) ? 1 : 0

    // inv-no-new-fp: EVERY tree other than the target keeps exactly its baseline
    // set — real repos and the two other mx5 states alike.
    const comparable = scans.filter(
        s => !s.label.includes(MX5_COMMITS.postAutofix) && !s.label.startsWith('fixture:')
    )
    const drifted = comparable.filter(s => !eq(s.baseline, s.treatment))
    const pre = byLabel(MX5_COMMITS.preAutofix)
    const fixture = (k: string): Scan | undefined => scans.find(s => s.label === `fixture:${k}`)
    const fixtureOk = (k: string): boolean => {
        const s = fixture(k)
        const want = FIXTURES.find(f => f.key === k)?.expectTreatment ?? []
        return s !== undefined && eq(s.treatment, [...want].map(p => `build.ts → ${p}`).sort())
    }
    const fixtureDetail = (k: string): string => {
        const s = fixture(k)
        return s === undefined ? 'fixture missing' : `got ${JSON.stringify(s.treatment)}`
    }

    const invariants: Invariant[] = [
        {
            label: 'inv-no-new-fp — every non-target tree keeps its baseline finding set',
            ok: drifted.length === 0,
            detail:
                drifted.length === 0
                    ? `${comparable.length} real tree(s) identical, ${FIXTURES.length} fixtures`
                    : drifted.map(s => s.label).join(', ')
        },
        {
            label: 'inv-run13-kept — the run-13 true positive still fires on mx5@4880e79',
            ok: pre !== undefined && pre.treatment.includes('src/server/index.ts → dist/index.html'),
            detail: pre === undefined ? 'tree unavailable' : pre.treatment.join(' | ') || '(none)'
        },
        {
            label: 'inv-scheme-urls-ignored — https:/data:/protocol-relative produce nothing',
            ok: fixtureOk('inv-scheme-urls-ignored'),
            detail: fixtureDetail('inv-scheme-urls-ignored')
        },
        {
            label: 'inv-non-build-html-ignored — an email-template literal is never scanned',
            ok: fixtureOk('inv-non-build-html-ignored'),
            detail: fixtureDetail('inv-non-build-html-ignored')
        },
        {
            label: 'inv-dev-only-is-dangling — a watch-only producer does not close a ref',
            ok: fixtureOk('inv-dev-only-is-dangling'),
            detail: fixtureDetail('inv-dev-only-is-dangling')
        },
        {
            label: 'ctl-production-producer-closes — a real build step DOES close the same ref',
            ok: fixtureOk('ctl-production-producer-closes'),
            detail: fixtureDetail('ctl-production-producer-closes')
        }
    ]

    reportAb({
        name: 'html-asset-closure (generated-HTML asset references)',
        reps: 1,
        targetShape:
            'a build script generates an HTML page referencing an asset the production '
            + 'build never emits, and the dangling-artifact checker reports nothing '
            + `(mx5@${MX5_COMMITS.postAutofix}: ${APP_CSS})`,
        baselineHits,
        treatmentHits,
        invariants
    })
}

await main()
